<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.2" />

  <Import Project="../../Build.props" />

  <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsAspireHost>true</IsAspireHost>
        <UserSecretsId>F06EC581-E178-477F-AE4E-8E508FC3CDE0</UserSecretsId>
        <RootNamespace>AppHost.AppHost</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost" Version="9.5.2" />
        <PackageReference Include="Aspire.Hosting.NodeJs" Version="9.5.2" />
        <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="9.5.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\WebApi\WebApi.csproj" />
    </ItemGroup>

</Project>
